FROM nodered/node-red:2.2.3
RUN npm install node-red-dashboard@3.6.5
RUN npm install node-red-contrib-ui-actions@0.1.8
RUN npm install node-red-node-ui-table@0.4.3
RUN npm install node-red-contrib-ui-level@0.1.46
